name: ckan-mqa
services:
  ckan2mqa:
    container_name: ckan-mqa-dev
    build:
      context: .
      dockerfile: ckan-mqa/Dockerfile.dev
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
          max-file: "10"
    ports:
      # debugpy
      - "${MQA_DEV_PORT}:${MQA_DEV_PORT}"
    volumes:
        - ./log:${APP_DIR}/log
        - ./ckan2mqa:${APP_DIR}/ckan2mqa
    network_mode: host