name: ckan-mqa
services:
  ckan2mqa:
    container_name: ckan-mqa
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/mjanez/ckan-mqa:latest
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
          max-file: "10"
    volumes:
        - ./log:${APP_DIR}/log
    restart: on-failure:3
    network_mode: host